### ISSUE TITLE
Superadmins should have a UI for creating tenant repositories

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#725]
When I log in/sign up at the top-level of hyku, I am superadmin, and in this role, I need to be able to create a tenant repo.

## Requirements

- [ ] Superadmins should be able to create a tenant
- [ ] Superadmins should be able to assign admins for tenants (by what mechanism is this done? Does a superadmin plug in one or more email addresses, at which point an activatation email is sent to complete user account creation within the tenant?)

### Optional

(These could be punted to follow-up tickets.)

- [ ] When a new application stack is created, there should be a method by which a user with superadmin role is created or assigned (we have a rake task for this per #733. does that suffice for now, @bbranan?)
- [ ] Superadmins should be able to grant superadmin role to other users (we have a rake task for this per #733. does that suffice for now, @bbranan?)
- [ ] Users without superadmin role should not be able to create tenants or grant superadmin rights (this is already ticketed as #735. Remove from this issue, @bbranan?)
- [x] Superadmins should be able to view a list of tenants. _Already exists under `/proprietor/accounts` path when logged in as superadmin_
- [ ] Superadmins should be able to view a list of admins within a tenant
- [ ] Superadmins should be able to remove tenant admin rights
- [x] Superadmins should be able to remove a tenant. _Already exists as an option under `/proprietor/accounts` path when logged in as superadmin_

**Comment by jcoyne** [comment]
If we remove this feature, what is the procedure for granting superadministrator access?

**Comment by hannahfrost** [comment]
On the call when this was discussed, it was mentioned that superadmin access was granted via the Rails console. For our demo site, for the time being, that seems like something we can live with until the specs for the superadmin UI are established.  Did I miss something?

**Comment by hannahfrost** [comment]
I just recast this ticket to address the fundamental bug. The two comments above this one no longer apply :)

**Comment by mjgiarlo** [comment]
@hannahfrost thanks! Remind me, is this for the MVP or post-MVP?

**Comment by mjgiarlo** [comment]
This is for the MVP per #728.

**Comment by mjgiarlo** [comment]
@jcoyne do you consider this actionable? Other than that it's blocked by #733.

**Comment by mjgiarlo** [comment]
The tenant creation process should include a new step where a superadmin can grant access to one or more tenant admin users. This last bit needs definition: by what mechanism is this done? Does a superadmin plug in one or more email addresses, at which point "stub" accounts are created and then when the tenant is created, email is sent to activate/complete user account creation within the tenant? (Does that make sense?)

@jcoyne @hannahfrost @ggeisler :arrow_up:

**Comment by hannahfrost** [comment]
I think that makes sense @mjgiarlo

**Comment by hannahfrost** [comment]
Discussed with @ggeisler . For the first pass on this UI, let's skip a formal design. We can revisit later and consider potential enhancement to the UI down the road. Moving to the ready column.

**Comment by hannahfrost** [comment]
@cbeer asked me for clearer requirements for this ticket. I'm going to discuss more with @bbranan this morning and follow up here.

**Comment by bbranan** [comment]
Requirements:

- When a new application stack is created, there must be a method by which a user with superadmin role is created or assigned
- Superadmins must be able to grant superadmin role to other users
- Superadmins must be able to create a tenant
- Superadmins must be able to assign admins for tenants
- Users without superadmin role must not be able to create tenants or grant superadmin rights

**Comment by bbranan** [comment]
Additional requirements:
- Superadmins must be able to remove tenant admin rights
- Superadmins must be able to remove a tenant

**Comment by mjgiarlo** [comment]
Good, @cbeer?

**Comment by tdonohue** [comment]
NOTE: As mentioned in today's standup, scaffolding for this feature is already in the codebase (including list/add/update/delete tenants).  If you are logged in as a superadmin (using "Administrator login" option in footer), you'll see an "Accounts" menu in header. That brings you to the `/proprietor/accounts` path, where the scaffolding exists.

**Comment by atz** [comment]
I think that we have failed to reconcile the choice of `Apartment` postgres schema segregation and the design expectations written here that involve variations of "see/do things across all tenants" or "superadmin can 'drop into' any tenant like a local user".  Neither of those things is currently possible, *by design*.  

A Hyku superadmin is not a Hyrax user.  There isn't a security model for what we are trying to do, because the existing security model is designed exactly to *prevent* a remote non-user from being able to access and alter fundamental administration of the system.  

As for an aggregate view, each tenant's data is in separate schemas, therefore separate tables.  And we cannot write a performant SQL query that says, e.g.:
```
SELECT id,email,display_name FROM '12341341-13-4-121-3412-413'.users 
UNION 
SELECT id,email,display_name FROM '98243543-77-3-565-8765-990'.users
UNION
...
```
because:
- we have to pre-query for all the namespaces
- `id`s will collide
- performance degrades as tenants/schemas are added
- all the same reasons that got the `Apartment` gem authors to abandon it, https://influitive.io/our-multi-tenancy-journey-with-postgres-schemas-and-apartment-6ecda151a21f

And it would be even *less* performant to attempt to do it via the app level using serial `switch` statements.  

There are a lot of things we *could* do to approach this problem, but I haven't seen us deal with the fundamental conflict of design here.  We said superadmin has no local rights.  Our chart reflects that.  But here we talk about local rights for both read and write?  I think we've gotten away from the title of this ticket, which **has** been met into scope creep territory.  We either need to respect our original design intention limiting the superuser (workaround: having a tenant-local admin user in each instance) or start seriously hacking at the security model at the Hyrax level.

**Comment by mjgiarlo** [comment]
@atz For those reasons and what we discussed last week, I am in favor of this ticket focusing on only the following two requirements:

- [ ] Superadmins should be able to create a tenant
- [ ] Superadmins should be able to create one or more admin accounts for tenants

**Comment by cbeer** [comment]
In case it's useful, I did some thinking about superadmins creating admin accounts earlier. Some WIP stuff is at https://github.com/projecthydra-labs/hyku/tree/superadmin-stash
